version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  static:
    external: true

services:
  nginx:
    image: nginx:1.18.0
    volumes:
      - "../nginx:/etc/nginx/conf.d"
      - "../static:/var/www/static"
    ports:
      - 8080:80
    depends_on:
      - glts_core
    networks:
      - app-network

  glts_core:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=2808
      - MYSQL_DATABASE=graphlabs_ts
    ports:
      - 3305:3306
    volumes:
      - "../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - app-network
    